/** Declaration file generated by dts-gen */

export class Circle {
    constructor(...args: any[]);
    componentWillMount(): void;
    getBounds(): any;
    getCenter(): any;
    getDraggable(): any;
    getEditable(): any;
    getMap(): any;
    getRadius(): any;
    getVisible(): any;
    render(): any;
}
export class DirectionsRenderer {
    constructor(...args: any[]);
    componentWillMount(): void;
    getDirections(): any;
    getPanel(): any;
    getRouteIndex(): any;
    render(): any;
}
export class DrawingManager {
    constructor(...args: any[]);
    componentWillMount(): void;
    getDrawingMode(): any;
    render(): any;
}
export class GoogleMap {
    constructor(...args: any[]);
    componentWillMount(): void;
    fitBounds(bounds: any): any;
    getBounds(): any;
    getCenter(): any;
    getDiv(): any;
    getHeading(): any;
    getMapTypeId(): any;
    getProjection(): any;
    getStreetView(): any;
    getTilt(): any;
    getZoom(): any;
    panBy(x: any, y: any): any;
    panTo(latLng: any): any;
    panToBounds(latLngBounds: any): any;
    render(): any;
}
export class GoogleMapLoader {
    constructor(...args: any[]);
    mountGoogleMap(domEl: any): void;
    render(): any;
    renderChild(): any;
    static defaultProps: {
        containerElement: {
            $$typeof: any;
            key: any;
            props: {
            };
            ref: any;
            type: string;
        };
    };
}
export class InfoWindow {
    constructor(...args: any[]);
    componentWillMount(): void;
    getContent(): void;
    getPosition(): any;
    getZIndex(): any;
    render(): any;
}
export class KmlLayer {
    constructor(...args: any[]);
    componentWillMount(): void;
    getDefaultViewport(): any;
    getMetadata(): any;
    getStatus(): any;
    getUrl(): any;
    getZIndex(): any;
    render(): any;
}
export class Marker {
    constructor(...args: any[]);
    componentWillMount(): void;
    componentWillUnmount(): void;
    getAnimation(): any;
    getAttribution(): any;
    getClickable(): any;
    getCursor(): any;
    getDraggable(): any;
    getIcon(): any;
    getLabel(): any;
    getOpacity(): any;
    getPlace(): any;
    getPosition(): any;
    getShape(): any;
    getTitle(): any;
    getVisible(): any;
    getZIndex(): any;
    render(): any;
}
export class OverlayView {
    constructor(...args: any[]);
    componentWillMount(): void;
    getPanes(): any;
    getProjection(): any;
    render(): any;
    static FLOAT_PANE: string;
    static MAP_PANE: string;
    static MARKER_LAYER: string;
    static OVERLAY_LAYER: string;
    static OVERLAY_MOUSE_TARGET: string;
    static defaultProps: {
        mapPaneName: any;
    };
}
export class Polygon {
    constructor(...args: any[]);
    componentWillMount(): void;
    getDraggable(): any;
    getEditable(): any;
    getPath(): any;
    getPaths(): any;
    getVisible(): any;
    render(): any;
}
export class Polyline {
    constructor(...args: any[]);
    componentWillMount(): void;
    getDraggable(): any;
    getEditable(): any;
    getPath(): any;
    getVisible(): any;
    render(): any;
}
export class Rectangle {
    constructor(...args: any[]);
    componentWillMount(): void;
    getBounds(): any;
    getDraggable(): any;
    getEditable(): any;
    getVisible(): any;
    render(): any;
}
export class SearchBox {
    constructor(...args: any[]);
    componentWillMount(): void;
    getBounds(): any;
    getPlaces(): any;
    render(): any;
}
export namespace Circle {
    namespace propTypes {
        function center(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultCenter(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultDraggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultEditable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultRadius(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultVisible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function draggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function editable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onCenterChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDblclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDrag(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragend(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragstart(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousedown(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousemove(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseout(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseover(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseup(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRadiusChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRightclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function radius(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function visible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace center {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultCenter {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultDraggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultEditable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultRadius {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultVisible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace draggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace editable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onCenterChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDblclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDrag {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragend {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragstart {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousedown {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousemove {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseout {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseover {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseup {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRadiusChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRightclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace radius {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace visible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace DirectionsRenderer {
    namespace propTypes {
        function defaultDirections(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPanel(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultRouteIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function directions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDirectionsChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function panel(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function routeIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace defaultDirections {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPanel {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultRouteIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace directions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDirectionsChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace panel {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace routeIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace DrawingManager {
    namespace propTypes {
        function defaultDrawingMode(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function drawingMode(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onCirclecomplete(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMarkercomplete(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onOverlaycomplete(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onPolygoncomplete(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onPolylinecomplete(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRectanglecomplete(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace defaultDrawingMode {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace drawingMode {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onCirclecomplete {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMarkercomplete {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onOverlaycomplete {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onPolygoncomplete {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onPolylinecomplete {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRectanglecomplete {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace GoogleMap {
    namespace propTypes {
        function center(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function containerProps(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function containerTagName(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultCenter(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultHeading(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultMapTypeId(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultStreetView(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultTilt(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultZoom(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function heading(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function map(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function mapTypeId(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onBoundsChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onCenterChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDblclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDrag(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragend(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragstart(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onHeadingChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onIdle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMaptypeidChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousemove(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseout(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseover(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onProjectionChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onResize(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRightclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onTilesloaded(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onTiltChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onZoomChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function streetView(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function tilt(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function zoom(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace center {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace containerProps {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace containerTagName {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultCenter {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultHeading {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultMapTypeId {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultStreetView {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultTilt {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultZoom {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace heading {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace map {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace mapTypeId {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onBoundsChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onCenterChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDblclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDrag {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragend {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragstart {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onHeadingChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onIdle {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMaptypeidChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousemove {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseout {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseover {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onProjectionChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onResize {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRightclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onTilesloaded {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onTiltChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onZoomChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace streetView {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace tilt {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace zoom {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace GoogleMapLoader {
    namespace propTypes {
        function containerElement(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function googleMapElement(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
    }
}
export namespace InfoWindow {
    namespace propTypes {
        function content(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultContent(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPosition(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultZIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onCloseclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onContentChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDomready(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onPositionChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onZindexChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function position(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function zIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace content {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultContent {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPosition {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultZIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onCloseclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onContentChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDomready {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onPositionChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onZindexChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace position {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace zIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace KmlLayer {
    namespace propTypes {
        function defaultDefaultViewport(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultMetadata(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultStatus(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultUrl(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultViewport(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultZIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function metadata(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDefaultviewportChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onStatusChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function status(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function url(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function zIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace defaultDefaultViewport {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultMetadata {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultStatus {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultUrl {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultViewport {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultZIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace metadata {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDefaultviewportChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onStatusChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace status {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace url {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace zIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace Marker {
    namespace propTypes {
        function animation(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function attribution(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function clickable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function cursor(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultAnimation(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultAttribution(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultClickable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultCursor(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultDraggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultIcon(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultLabel(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOpacity(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPlace(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPosition(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultShape(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultTitle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultVisible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultZIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function draggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function icon(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function label(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onAnimationChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClickableChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onCursorChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDblclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDrag(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragend(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDraggableChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragstart(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onFlatChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onIconChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousedown(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseout(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseover(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseup(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onPositionChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRightclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onShapeChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onTitleChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onVisibleChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onZindexChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function opacity(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function place(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function position(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function shape(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function title(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function visible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function zIndex(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace animation {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace attribution {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace clickable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace cursor {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultAnimation {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultAttribution {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultClickable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultCursor {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultDraggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultIcon {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultLabel {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOpacity {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPlace {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPosition {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultShape {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultTitle {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultVisible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultZIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace draggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace icon {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace label {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onAnimationChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClickableChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onCursorChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDblclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDrag {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragend {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDraggableChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragstart {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onFlatChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onIconChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousedown {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseout {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseover {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseup {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onPositionChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRightclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onShapeChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onTitleChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onVisibleChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onZindexChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace opacity {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace place {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace position {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace shape {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace title {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace visible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace zIndex {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace OverlayView {
    namespace propTypes {
        function bounds(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function children(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultBounds(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultChildren(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultGetPixelPositionOffset(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultMapPaneName(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPosition(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function getPixelPositionOffset(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function mapPaneName(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function position(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace bounds {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace children {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultBounds {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultChildren {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultGetPixelPositionOffset {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultMapPaneName {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPosition {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace getPixelPositionOffset {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace mapPaneName {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace position {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace Polygon {
    namespace propTypes {
        function defaultDraggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultEditable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPath(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPaths(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultVisible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function draggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function editable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDblclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDrag(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragend(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragstart(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousedown(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousemove(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseout(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseover(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseup(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRightclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function path(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function paths(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function visible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace defaultDraggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultEditable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPath {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPaths {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultVisible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace draggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace editable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDblclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDrag {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragend {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragstart {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousedown {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousemove {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseout {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseover {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseup {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRightclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace path {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace paths {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace visible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace Polyline {
    namespace propTypes {
        function defaultDraggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultEditable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultPath(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultVisible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function draggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function editable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDblclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDrag(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragend(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragstart(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousedown(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousemove(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseout(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseover(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseup(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRightclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function path(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function visible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace defaultDraggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultEditable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultPath {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultVisible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace draggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace editable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDblclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDrag {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragend {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragstart {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousedown {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousemove {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseout {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseover {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseup {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRightclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace path {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace visible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace Rectangle {
    namespace propTypes {
        function bounds(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultBounds(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultDraggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultEditable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultOptions(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultVisible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function draggable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function editable(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onBoundsChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onClick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDblclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDrag(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragend(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onDragstart(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousedown(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMousemove(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseout(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseover(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onMouseup(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onRightclick(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function options(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function visible(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace bounds {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultBounds {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultDraggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultEditable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultOptions {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultVisible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace draggable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace editable {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onBoundsChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onClick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDblclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDrag {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragend {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onDragstart {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousedown {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMousemove {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseout {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseover {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onMouseup {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onRightclick {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace options {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace visible {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
export namespace SearchBox {
    namespace propTypes {
        function bounds(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function defaultBounds(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onPlacesChanged(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace bounds {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace defaultBounds {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onPlacesChanged {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
